import { apiResponse, bearerAuth, idempotencyKey, jsonBody, ref, standardResponses } from "./shared";

const serverUrl = process.env.NEXT_PUBLIC_CENTRAL_BANK_URL || "http://localhost:3000";
const auth = [{ bearerAuth: [] }];
const financialAuth = [{ bearerAuth: [], idempotencyKey: [] }];
const op = (tag: string, summary: string, options: Record<string, unknown> = {}) => ({
  tags: [tag], summary, security: auth, responses: standardResponses, ...options,
});
const bodyOp = (tag: string, summary: string, schema: string, financial = false) => op(tag, summary, {
  security: financial ? financialAuth : auth,
  requestBody: jsonBody(ref(schema)),
});
const pathParam = (name: string, description = `${name} resource`) => ({
  name, in: "path", required: true, description, schema: { type: "string" },
});
const query = (name: string, type = "string") => ({ name, in: "query", required: false, schema: { type } });

export const centralBankSpec = {
  openapi: "3.1.0",
  info: {
    title: "SmartBank Central Bank Core API",
    version: "1.0.0",
    description: "API sumber kebenaran saldo, money supply, settlement, ledger, kredit, dan operasi petugas. Nilai uang dikirim sebagai string/integer minor-unit dan tidak menggunakan floating point. Semua POST finansial membutuhkan Idempotency-Key.",
  },
  servers: [{ url: serverUrl, description: "Central Bank Core" }],
  tags: ["Health", "Auth", "Wallet", "Transfer", "Payment Request", "Loans", "Teller", "Manager", "Central Bank", "Fees", "Notifications", "Internal", "Algorithms"].map((name) => ({ name })),
  components: {
    securitySchemes: {
      bearerAuth,
      idempotencyKey,
      serviceToken: { type: "apiKey", in: "header", name: "X-Service-Token", description: "Shared token khusus komunikasi antarlayanan" },
    },
    schemas: {
      ApiResponse: apiResponse,
      Money: { oneOf: [{ type: "integer" }, { type: "string", pattern: "^[0-9]+$" }], example: "50000", description: "Nominal integer dalam minor unit" },
      Register: { type: "object", required: ["name", "email", "phone", "password"], properties: { name: { type: "string" }, email: { type: "string", format: "email" }, phone: { type: "string", example: "+628123456789" }, password: { type: "string", format: "password", minLength: 8 }, role: { type: "string" } } },
      Login: { type: "object", required: ["email", "password"], properties: { email: { type: "string", format: "email" }, password: { type: "string", format: "password" } } },
      Amount: { type: "object", required: ["amount"], properties: { amount: ref("Money") } },
      Transfer: { type: "object", required: ["to_wallet_id", "amount"], properties: { to_wallet_id: { type: "string", format: "uuid" }, amount: ref("Money"), note: { type: "string", maxLength: 500 } } },
      PaymentRequest: { type: "object", required: ["payee_wallet_id", "amount"], properties: { payee_wallet_id: { type: "string", format: "uuid" }, amount: ref("Money"), description: { type: "string" }, expires_at: { type: "string", format: "date-time" } } },
      UpgradeRequest: { type: "object", required: ["role"], properties: { role: { type: "string" }, businessName: { type: "string" }, nik: { type: "string" } } },
      ManagerUserAction: { type: "object", required: ["userId", "reasonCode"], properties: { userId: { type: "string" }, reasonCode: { type: "string" } } },
      ManagerLoanAction: { type: "object", required: ["loanId", "reasonCode"], properties: { loanId: { type: "string" }, reasonCode: { type: "string" } } },
      TellerAction: { type: "object", required: ["userId", "amount", "reasonCode"], properties: { userId: { type: "string" }, amount: ref("Money"), reasonCode: { type: "string" } } },
      KycAction: { type: "object", required: ["userId"], properties: { userId: { type: "string" }, reasonCode: { type: "string" }, approvedRole: { type: "string" } } },
      Reversal: { type: "object", required: ["original_transaction_id", "reason_code"], properties: { original_transaction_id: { type: "string" }, reason_code: { type: "string" } } },
      Issuance: { type: "object", required: ["target_wallet_id", "amount", "reason_code"], properties: { target_wallet_id: { type: "string" }, amount: ref("Money"), reason_code: { type: "string" }, note: { type: "string" } } },
      Burn: { type: "object", required: ["source_wallet_id", "amount", "reason_code"], properties: { source_wallet_id: { type: "string" }, amount: ref("Money"), reason_code: { type: "string" }, note: { type: "string" } } },
      FeeQuote: { type: "object", required: ["source_app", "amount"], properties: { source_app: { type: "string" }, amount: ref("Money") } },
      FeeConfiguration: { type: "object", required: ["type", "mode", "value"], properties: { type: { type: "string" }, mode: { type: "string" }, value: ref("Money"), min_fee: ref("Money"), max_fee: ref("Money"), is_active: { type: "boolean" } } },
      Notification: { type: "object", required: ["user_id", "type", "title", "body"], properties: { user_id: { type: "string" }, type: { type: "string" }, source_app: { type: "string" }, source_ref: { type: "string" }, title: { type: "string" }, body: { type: "string" }, payload: { type: "object", additionalProperties: true } } },
      InternalSettlement: { type: "object", additionalProperties: true, description: "Payload settlement antarlayanan; gunakan kontrak integrasi service yang memanggil endpoint ini." },
      GraphTrace: { type: "object", required: ["graph", "start"], properties: { graph: { type: "object", additionalProperties: { type: "array", items: { type: "string" } } }, start: { type: "string" }, target: { type: "string" }, maxDepth: { type: "integer" } } },
      KmpSearch: { type: "object", required: ["text", "pattern"], properties: { text: { type: "string" }, pattern: { type: "string" }, caseInsensitive: { type: "boolean", default: true } } },
      Candidates: { type: "object", required: ["candidates"], properties: { candidates: { type: "array", items: { type: "object", additionalProperties: true } }, k: { type: "integer" } } },
    },
  },
  paths: {
    "/api/v1/health": { get: op("Health", "Status Central Bank", { security: [] }) },
    "/api/v1/auth/register": { post: bodyOp("Auth", "Registrasi pengguna", "Register", true) },
    "/api/v1/auth/login": { post: bodyOp("Auth", "Login dan memperoleh JWT", "Login") },
    "/api/v1/wallets/me/balance": { get: op("Wallet", "Saldo wallet pengguna") },
    "/api/v1/wallets/me/transactions": { get: op("Wallet", "Riwayat transaksi pengguna") },
    "/api/v1/wallets/me/upgrade-request": { post: bodyOp("Wallet", "Ajukan upgrade akun", "UpgradeRequest") },
    "/api/v1/users/by-account/{accountNumber}": { get: op("Wallet", "Cari wallet berdasarkan nomor rekening", { parameters: [pathParam("accountNumber", "Nomor rekening 10 digit")] }) },
    "/api/v1/users/{id}/wallet": { get: op("Internal", "Cari wallet berdasarkan user ID", { security: [{ serviceToken: [] }], parameters: [pathParam("id", "User ID")] }) },
    "/api/v1/internal/users/by-phone/{phone}": { get: op("Internal", "Cari pengguna berdasarkan telepon", { security: [{ serviceToken: [] }], parameters: [pathParam("phone", "Nomor telepon URL-encoded")] }) },
    "/api/v1/transfers": { post: bodyOp("Transfer", "Settlement transfer antardompet", "Transfer", true) },
    "/api/v1/payment-requests": { post: bodyOp("Payment Request", "Buat payment request", "PaymentRequest", true) },
    "/api/v1/payment-requests/{id}/pay": { post: op("Payment Request", "Bayar payment request", { security: financialAuth, parameters: [pathParam("id")] }) },
    "/api/v1/loans/me": { get: op("Loans", "Daftar pinjaman pengguna") },
    "/api/v1/loans/me/limit": { get: op("Loans", "Limit pinjaman pengguna") },
    "/api/v1/loans/apply": { post: bodyOp("Loans", "Ajukan pinjaman", "Amount", true) },
    "/api/v1/loans/{id}/repay": { post: bodyOp("Loans", "Bayar pinjaman", "Amount", true), parameters: [pathParam("id")] },
    "/api/v1/teller/customer": { get: op("Teller", "Cari nasabah", { parameters: [query("query")] }) },
    "/api/v1/teller/kyc/verify": { post: bodyOp("Teller", "Verifikasi KYC", "KycAction") },
    "/api/v1/teller/top-up": { post: bodyOp("Teller", "Top-up oleh teller", "TellerAction", true) },
    "/api/v1/teller/withdraw": { post: bodyOp("Teller", "Penarikan oleh teller", "TellerAction", true) },
    "/api/v1/teller/kyc/approve": { post: bodyOp("Teller", "Setujui KYC", "KycAction") },
    "/api/v1/teller/kyc/reject": { post: bodyOp("Teller", "Tolak KYC", "KycAction") },
    "/api/v1/teller/loans/pending": { get: op("Teller", "Daftar pinjaman pending", { parameters: [query("max_amount")] }) },
    "/api/v1/teller/loans/{id}/recommend": { post: op("Teller", "Rekomendasikan pinjaman", { parameters: [pathParam("id")], requestBody: jsonBody({ type: "object", properties: { note: { type: "string" } } }, false) }) },
    "/api/v1/manager/loan-pool": { get: op("Manager", "Saldo loan pool") },
    "/api/v1/manager/loans/pending": { get: op("Manager", "Daftar pinjaman pending", { parameters: [query("min_amount"), query("recommended", "boolean")] }) },
    "/api/v1/manager/users/suspend": { post: bodyOp("Manager", "Suspend pengguna", "ManagerUserAction") },
    "/api/v1/manager/users/activate": { post: bodyOp("Manager", "Aktifkan pengguna", "ManagerUserAction") },
    "/api/v1/manager/loans/approve": { post: bodyOp("Manager", "Setujui pinjaman", "ManagerLoanAction", true) },
    "/api/v1/manager/loans/reject": { post: bodyOp("Manager", "Tolak pinjaman", "ManagerLoanAction", true) },
    "/api/v1/central-bank/supply": { get: op("Central Bank", "Invariant money supply") },
    "/api/v1/central-bank/ledger": { get: op("Central Bank", "Daftar ledger", { parameters: [query("account_id"), query("transaction_id"), query("from"), query("to")] }) },
    "/api/v1/central-bank/wallets": { get: op("Central Bank", "Daftar wallet", { parameters: [query("account_type"), query("search")] }) },
    "/api/v1/central-bank/transactions": { get: op("Central Bank", "Daftar transaksi", { parameters: [query("limit", "integer")] }) },
    "/api/v1/central-bank/reversals": { post: bodyOp("Central Bank", "Reverse transaksi", "Reversal", true) },
    "/api/v1/central-bank/issuance": { post: bodyOp("Central Bank", "Terbitkan currency", "Issuance", true) },
    "/api/v1/central-bank/burn": { post: bodyOp("Central Bank", "Burn currency", "Burn", true) },
    "/api/v1/central-bank/fees": { get: op("Central Bank", "Daftar konfigurasi fee"), put: bodyOp("Central Bank", "Ubah konfigurasi fee", "FeeConfiguration") },
    "/api/v1/central-bank/fees/{type}": { get: op("Central Bank", "Detail konfigurasi fee", { parameters: [pathParam("type")] }) },
    "/api/v1/central-bank/audit-logs": { get: op("Central Bank", "Daftar audit log", { parameters: [query("search"), query("service_name"), query("limit", "integer")] }) },
    "/api/v1/fees/quote": { post: bodyOp("Fees", "Hitung quote fee", "FeeQuote") },
    "/api/v1/internal/notifications": { post: op("Internal", "Buat notifikasi internal", { security: [{ serviceToken: [] }], requestBody: jsonBody(ref("Notification")) }) },
    "/api/v1/internal/payment-requests/settle": { post: op("Internal", "Settlement payment request antarlayanan", { security: [{ serviceToken: [] }, { idempotencyKey: [] }], requestBody: jsonBody(ref("InternalSettlement")) }) },
    "/api/v1/users/me/notifications": { get: op("Notifications", "Daftar notifikasi", { parameters: [query("type"), query("unread_only", "boolean"), query("page", "integer"), query("limit", "integer")] }) },
    "/api/v1/users/me/notifications/unread-count": { get: op("Notifications", "Jumlah notifikasi belum dibaca") },
    "/api/v1/users/me/notifications/{id}/read": { patch: op("Notifications", "Tandai notifikasi telah dibaca", { parameters: [pathParam("id")] }) },
    "/api/v1/users/me/notifications/read-all": { post: op("Notifications", "Tandai semua notifikasi telah dibaca") },
    "/api/v1/algorithms/graph/trace": { post: bodyOp("Algorithms", "BFS graph trace", "GraphTrace") },
    "/api/v1/algorithms/graph/shortest-path": { post: bodyOp("Algorithms", "BFS shortest path", "GraphTrace") },
    "/api/v1/algorithms/graph/chains": { post: bodyOp("Algorithms", "DFS graph chains", "GraphTrace") },
    "/api/v1/algorithms/kmp/search": { post: bodyOp("Algorithms", "KMP text search", "KmpSearch") },
    "/api/v1/algorithms/kmp/prefix": { post: op("Algorithms", "KMP prefix table", { requestBody: jsonBody({ type: "object", required: ["pattern"], properties: { pattern: { type: "string" } } }) }) },
    "/api/v1/algorithms/greedy/prioritize": { post: bodyOp("Algorithms", "Prioritaskan kandidat audit", "Candidates") },
    "/api/v1/algorithms/greedy/select-top-k": { post: bodyOp("Algorithms", "Pilih kandidat audit top-K", "Candidates") },
    "/api/v1/algorithms/info": { get: op("Algorithms", "Informasi algoritma") },
  },
};
